apiVersion: 1

datasources:
  - name: Pulse-Postgres
    type: postgres
    uid: pulse_pg
    url: postgres:5432
    database: pulse
    user: pulse
    secureJsonData:
      password: pulse
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: false
